# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - store

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install composer
        run: composer install --no-dev --optimize-autoloader

      - name: Prepare build
        run: |
          mkdir build
          cp -R app bootstrap config database public resources routes storage vendor artisan composer.json composer.lock build/
          cp -R public build/public

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'store'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_594FAB6C747F4BCEB170649394D65DE0 }}
